import React, { useState, useMemo, useEffect } from 'react';
import {
  Activity,
  Cpu,
  Lightbulb,
  Dna,
  RefreshCw,
  TrendingUp,
  BarChart3,
  Sliders,
  Play,
  Copy,
  Check,
  Download,
  Terminal,
  Shield,
  Layers,
  ArrowUpRight,
  ArrowDownRight,
  ChevronRight,
  DollarSign
} from 'lucide-react';

import { Candle, Timeframe, StrategyParams, Trade, PerformanceMetrics, PaperTrade } from './types/quant';
import { generateBaseNQData, resampleDataInMemory, NQ_SPECS } from './utils/nqDataGenerator';
import {
  executeBacktest,
  runMonteCarloSimulation,
  runGeneticOptimizer,
  runWalkForwardEngine
} from './utils/quantEngine';
import { TradingViewChart } from './components/TradingViewChart';
import {
  EquityCurveChart,
  DrawdownChart,
  MonteCarloChart,
  TradeDistributionChart
} from './components/InteractiveCharts';
import { StreamlitSourceModal } from './components/StreamlitSourceModal';

export default function App() {
  // Global Timeframe Resampler State
  const [selectedTimeframe, setSelectedTimeframe] = useState<Timeframe>('15m');
  const [activeTab, setActiveTab] = useState<'backtest' | 'ideas' | 'optimizer' | 'wfo' | 'benchmark' | 'papertrading'>('backtest');
  const [isSourceModalOpen, setIsSourceModalOpen] = useState(false);

  // Capital & Position Controls
  const [startingCapital, setStartingCapital] = useState<number>(100000);
  const [nqContracts, setNqContracts] = useState<number>(1);

  // Generate Base 2022-2026 NQ Data once in memory
  const baseNQData = useMemo(() => generateBaseNQData(), []);

  // In-Memory Resampled Data
  const resampledData = useMemo(() => {
    return resampleDataInMemory(baseNQData, selectedTimeframe);
  }, [baseNQData, selectedTimeframe]);

  const latestCandle = resampledData[resampledData.length - 1] || { close: 25200, open: 25150 };

  // ==========================================
  // TAB 1: STRATEGY BACKTEST STATE
  // ==========================================
  const [strategyCode, setStrategyCode] = useState<string>(`# QuantLab Institutional Strategy
# Target Asset: CME Globex Nasdaq-100 (NQ) Futures
# Friction: $2.05 comm/side + 1-tick slippage

fast_ema = 14
slow_ema = 34
rsi_period = 14
rsi_lower = 38.0
rsi_upper = 62.0
`);

  const [parsedParams, setParsedParams] = useState<StrategyParams>({
    fastEma: 14,
    slowEma: 34,
    rsiPeriod: 14,
    rsiLower: 38,
    rsiUpper: 62,
    contracts: 1,
  });

  // Parse code parameters safely
  const handleParseAndRun = (codeToRun?: string) => {
    const code = codeToRun || strategyCode;
    const lines = code.split('\n');
    const newParams = { ...parsedParams, contracts: nqContracts };

    for (const line of lines) {
      const trimmed = line.trim();
      if (trimmed.includes('=') && !trimmed.startsWith('#')) {
        const [key, val] = trimmed.split('=').map(s => s.trim().split('#')[0].trim());
        const num = parseFloat(val);
        if (!isNaN(num)) {
          if (key === 'fast_ema') newParams.fastEma = Math.max(3, Math.round(num));
          if (key === 'slow_ema') newParams.slowEma = Math.max(newParams.fastEma + 1, Math.round(num));
          if (key === 'rsi_period') newParams.rsiPeriod = Math.max(3, Math.round(num));
          if (key === 'rsi_lower') newParams.rsiLower = num;
          if (key === 'rsi_upper') newParams.rsiUpper = num;
        }
      }
    }
    setParsedParams(newParams);
  };

  // Run backtest
  const { trades, metrics } = useMemo(() => {
    return executeBacktest(resampledData, { ...parsedParams, contracts: nqContracts }, startingCapital);
  }, [resampledData, parsedParams, nqContracts, startingCapital]);

  // Monte Carlo Simulation
  const monteCarlo = useMemo(() => {
    return runMonteCarloSimulation(trades, startingCapital, 100);
  }, [trades, startingCapital]);

  // ==========================================
  // TAB 2: AI IDEAS BOT STATE
  // ==========================================
  const [ideaPrompt, setIdeaPrompt] = useState<string>(
    'Build a Nasdaq-100 breakout strategy based on dynamic VWAP bands and ATR volatility expansion during the US regular session, with a 2:1 profit-to-risk ratio and strict friction accounting.'
  );
  const [selectedConcept, setSelectedConcept] = useState<string>('ORB');
  const [generatedCode, setGeneratedCode] = useState<string>(`# Generated by QuantLab AI Ideas Engine
# Model: NQ London & US Session Volatility Breakout
# Friction: $14.10 per round-trip trade

fast_ema = 12
slow_ema = 28
rsi_period = 14
rsi_lower = 35.0
rsi_upper = 65.0
`);
  const [codeCopied, setCodeCopied] = useState(false);

  const handleGenerateIdea = () => {
    if (selectedConcept === 'ORB') {
      setGeneratedCode(`# Strategy: NQ Opening Range Breakout (ORB)
fast_ema = 9
slow_ema = 21
rsi_period = 10
rsi_lower = 32.0
rsi_upper = 68.0
`);
    } else if (selectedConcept === 'VWAP') {
      setGeneratedCode(`# Strategy: Session VWAP 2.0-Sigma Mean Reversion
fast_ema = 16
slow_ema = 44
rsi_period = 14
rsi_lower = 40.0
rsi_upper = 60.0
`);
    } else if (selectedConcept === 'MOMENTUM') {
      setGeneratedCode(`# Strategy: Supertrend 3x ATR Momentum Flow
fast_ema = 14
slow_ema = 38
rsi_period = 14
rsi_lower = 36.0
rsi_upper = 64.0
`);
    }
  };

  const handleSendToBacktest = () => {
    setStrategyCode(generatedCode);
    handleParseAndRun(generatedCode);
    setActiveTab('backtest');
  };

  // ==========================================
  // TAB 3: STRATEGY OPTIMIZER STATE
  // ==========================================
  const [optimizerObjective, setOptimizerObjective] = useState<'sharpe' | 'profitFactor' | 'netPnL'>('sharpe');
  const topVariants = useMemo(() => {
    return runGeneticOptimizer(resampledData, 10000);
  }, [resampledData]);

  const [optCopied, setOptCopied] = useState(false);

  // ==========================================
  // TAB 4: WALK-FORWARD OPTIMIZATION (WFO)
  // ==========================================
  const [wfoSplits, setWfoSplits] = useState<number>(5);
  const [wfoIsRatio, setWfoIsRatio] = useState<number>(0.7);
  const wfoResult = useMemo(() => {
    return runWalkForwardEngine(resampledData, wfoSplits, wfoIsRatio);
  }, [resampledData, wfoSplits, wfoIsRatio]);

  // ==========================================
  // TAB 5: BENCHMARK ALPHA & BETA
  // ==========================================
  const benchmarkStats = useMemo(() => {
    if (resampledData.length === 0) return { bhReturn: 0, alpha: 0, beta: 0.38, bhEquity: [100000] };
    const firstClose = resampledData[0].close;
    const lastClose = resampledData[resampledData.length - 1].close;
    const bhReturn = ((lastClose / firstClose) - 1) * 100;
    const stratReturn = metrics.netPnLPct;
    const beta = 0.38; // Typical market sensitivity
    const alpha = (stratReturn / 3.7) - (beta * (bhReturn / 3.7));

    const bhEquity = resampledData.map(c => (c.close / firstClose) * startingCapital);
    return { bhReturn, alpha, beta, bhEquity };
  }, [resampledData, metrics, startingCapital]);

  // ==========================================
  // TAB 6: MANUAL PAPER TRADING STATE
  // ==========================================
  const [paperBalance, setPaperBalance] = useState<number>(100000);
  const [paperPosition, setPaperPosition] = useState<'FLAT' | 'LONG' | 'SHORT'>('FLAT');
  const [paperContracts, setPaperContracts] = useState<number>(1);
  const [paperEntryPrice, setPaperEntryPrice] = useState<number>(0);
  const [paperTrades, setPaperTrades] = useState<PaperTrade[]>([]);
  const [isSessionFinished, setIsSessionFinished] = useState<boolean>(false);

  // Unrealized PnL
  const unrealizedPnL = useMemo(() => {
    if (paperPosition === 'FLAT') return 0;
    const diff = paperPosition === 'LONG'
      ? latestCandle.close - paperEntryPrice
      : paperEntryPrice - latestCandle.close;
    return diff * NQ_SPECS.multiplier * paperContracts;
  }, [paperPosition, paperEntryPrice, latestCandle.close, paperContracts]);

  // Order Executions
  const handleBuyMarket = () => {
    const fillPrice = latestCandle.close + (NQ_SPECS.tickSize * NQ_SPECS.slippageTicks);
    if (paperPosition === 'SHORT') {
      // Cover Short
      const diff = paperEntryPrice - fillPrice;
      const gross = diff * NQ_SPECS.multiplier * paperContracts;
      const friction = NQ_SPECS.roundTripFriction * paperContracts;
      const net = gross - friction;
      setPaperBalance(prev => prev + net);
      setPaperTrades(prev => [
        {
          id: `ORD-${prev.length + 1}`,
          type: 'COVER_SHORT',
          entryTime: 'Open',
          exitTime: latestCandle.dateStr,
          entryPrice: paperEntryPrice,
          exitPrice: fillPrice,
          contracts: paperContracts,
          grossPnL: gross,
          friction,
          netPnL: net,
        },
        ...prev,
      ]);
      setPaperPosition('FLAT');
    } else {
      // Open Long
      setPaperPosition('LONG');
      setPaperEntryPrice(fillPrice);
    }
  };

  const handleSellMarket = () => {
    const fillPrice = latestCandle.close - (NQ_SPECS.tickSize * NQ_SPECS.slippageTicks);
    if (paperPosition === 'LONG') {
      // Close Long
      const diff = fillPrice - paperEntryPrice;
      const gross = diff * NQ_SPECS.multiplier * paperContracts;
      const friction = NQ_SPECS.roundTripFriction * paperContracts;
      const net = gross - friction;
      setPaperBalance(prev => prev + net);
      setPaperTrades(prev => [
        {
          id: `ORD-${prev.length + 1}`,
          type: 'SELL_LONG',
          entryTime: 'Open',
          exitTime: latestCandle.dateStr,
          entryPrice: paperEntryPrice,
          exitPrice: fillPrice,
          contracts: paperContracts,
          grossPnL: gross,
          friction,
          netPnL: net,
        },
        ...prev,
      ]);
      setPaperPosition('FLAT');
    } else {
      // Open Short
      setPaperPosition('SHORT');
      setPaperEntryPrice(fillPrice);
    }
  };

  const handleCloseMarket = () => {
    if (paperPosition === 'FLAT') return;
    const slip = NQ_SPECS.tickSize * NQ_SPECS.slippageTicks;
    const fillPrice = paperPosition === 'LONG' ? latestCandle.close - slip : latestCandle.close + slip;
    const diff = paperPosition === 'LONG' ? fillPrice - paperEntryPrice : paperEntryPrice - fillPrice;
    const gross = diff * NQ_SPECS.multiplier * paperContracts;
    const friction = NQ_SPECS.roundTripFriction * paperContracts;
    const net = gross - friction;

    setPaperBalance(prev => prev + net);
    setPaperTrades(prev => [
      {
        id: `ORD-${prev.length + 1}`,
        type: 'CLOSE_MARKET',
        entryTime: 'Open',
        exitTime: latestCandle.dateStr,
        entryPrice: paperEntryPrice,
        exitPrice: fillPrice,
        contracts: paperContracts,
        grossPnL: gross,
        friction,
        netPnL: net,
      },
      ...prev,
    ]);
    setPaperPosition('FLAT');
  };

  const handleFinishSession = () => {
    if (paperPosition !== 'FLAT') {
      handleCloseMarket();
    }
    setIsSessionFinished(true);
  };

  const handleResetSession = () => {
    setPaperBalance(startingCapital);
    setPaperPosition('FLAT');
    setPaperEntryPrice(0);
    setPaperTrades([]);
    setIsSessionFinished(false);
  };

  return (
    <div className="min-h-screen bg-[#080C14] text-slate-100 flex flex-col font-sans">
      {/* ========================================================= */}
      {/* 1. TOP BAR CONTRACT (Strict 3 Zones: Brand - Nav - Action) */}
      {/* ========================================================= */}
      <header className="h-14 border-b border-white/[0.08] bg-[#090D14]/90 backdrop-blur sticky top-0 z-40 px-5 flex items-center justify-between">
        {/* Zone 1: Single text element wordmark */}
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-2">
            <div className="w-7 h-7 rounded bg-gradient-to-br from-sky-500 to-cyan-400 flex items-center justify-center font-mono font-bold text-black text-xs shadow-sm">
              NQ
            </div>
            <span className="font-bold tracking-tight text-white text-base">NQ QuantLab</span>
          </div>
          <div className="hidden sm:flex items-center gap-2 text-xs text-slate-500 font-mono">
            <span>CME Globex</span>
            <span>·</span>
            <span>2022–2026</span>
          </div>
        </div>

        {/* Zone 2: Navigation Links / Segmented Tabs */}
        <nav className="hidden lg:flex items-center gap-1 bg-[#0E1626] p-1 rounded-lg border border-white/[0.06]">
          {[
            { id: 'backtest', label: 'Backtest Bot', icon: Activity },
            { id: 'ideas', label: 'Ideas Bot', icon: Lightbulb },
            { id: 'optimizer', label: 'Optimizer', icon: Dna },
            { id: 'wfo', label: 'WFO Engine', icon: RefreshCw },
            { id: 'benchmark', label: 'Alpha / Beta', icon: TrendingUp },
            { id: 'papertrading', label: 'Paper Terminal', icon: BarChart3 },
          ].map(tab => {
            const Icon = tab.icon;
            const isActive = activeTab === tab.id;
            return (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id as any)}
                className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-medium whitespace-nowrap transition-colors ${
                  isActive
                    ? 'bg-sky-500/20 text-sky-400 font-semibold shadow-sm'
                    : 'text-slate-400 hover:text-slate-200'
                }`}
              >
                <Icon className="w-3.5 h-3.5" />
                <span>{tab.label}</span>
              </button>
            );
          })}
        </nav>

        {/* Zone 3: Primary Action & Live NQ Price */}
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-2 font-mono text-xs bg-[#0E1626] px-3 py-1.5 rounded-md border border-white/[0.06]">
            <span className="text-slate-500">NQ</span>
            <span className="font-bold text-sky-400">{latestCandle.close.toFixed(2)}</span>
          </div>

          <button
            onClick={() => setIsSourceModalOpen(true)}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold text-white bg-sky-600 hover:bg-sky-500 rounded-md transition-colors shadow-sm whitespace-nowrap"
          >
            <Terminal className="w-3.5 h-3.5" />
            <span className="hidden sm:inline">Streamlit Source (.py)</span>
          </button>
        </div>
      </header>

      {/* Mobile Tab Scroller */}
      <div className="lg:hidden flex items-center gap-1 overflow-x-auto p-2 bg-[#0B111D] border-b border-white/[0.06]">
        {[
          { id: 'backtest', label: 'Backtest' },
          { id: 'ideas', label: 'Ideas' },
          { id: 'optimizer', label: 'Optimizer' },
          { id: 'wfo', label: 'WFO' },
          { id: 'benchmark', label: 'Benchmark' },
          { id: 'papertrading', label: 'Paper' },
        ].map(tab => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id as any)}
            className={`px-3 py-1 text-xs font-medium rounded-md whitespace-nowrap ${
              activeTab === tab.id ? 'bg-sky-500/20 text-sky-400 font-semibold' : 'text-slate-400'
            }`}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {/* ========================================================= */}
      {/* 2. MAIN WORKSPACE WITH SIDEBAR CONTROLS */}
      {/* ========================================================= */}
      <div className="flex-1 flex flex-col md:flex-row overflow-hidden">
        {/* Left Sidebar: Controls & Resampler */}
        <aside className="w-full md:w-64 lg:w-72 bg-[#0B111D] border-r border-white/[0.08] p-4 flex flex-col gap-5 shrink-0 overflow-y-auto">
          {/* Global Timeframe Resampler */}
          <div className="space-y-2">
            <div className="flex items-center justify-between text-xs font-semibold text-slate-400 uppercase tracking-wider">
              <span>Timeframe Resampler</span>
              <span className="text-[10px] text-sky-400 font-mono">In-Memory</span>
            </div>
            <div className="grid grid-cols-4 gap-1.5">
              {(['5m', '15m', '30m', '45m', '1h', '2h', '4h', '1d'] as Timeframe[]).map(tf => (
                <button
                  key={tf}
                  onClick={() => setSelectedTimeframe(tf)}
                  className={`py-1.5 text-xs font-mono font-medium rounded transition-colors ${
                    selectedTimeframe === tf
                      ? 'bg-sky-500/20 text-sky-400 border border-sky-500/40 font-bold'
                      : 'bg-[#0E1626] text-slate-400 hover:text-white border border-white/[0.04]'
                  }`}
                >
                  {tf}
                </button>
              ))}
            </div>
            <p className="text-[11px] text-slate-500">
              Dynamically resamples OHLCV bars strictly in RAM. All tabs automatically inherit.
            </p>
          </div>

          {/* Institutional NQ Specifications Card */}
          <div className="rounded-lg border border-white/[0.08] bg-[#0E1626] p-3.5 space-y-2.5">
            <div className="flex items-center justify-between text-xs font-bold text-slate-300">
              <span className="flex items-center gap-1.5">
                <Shield className="w-3.5 h-3.5 text-sky-400" />
                <span>CME NQ Specifications</span>
              </span>
              <span className="font-mono text-sky-400">$20.00/pt</span>
            </div>

            <div className="space-y-1.5 text-xs font-mono">
              <div className="flex justify-between text-slate-400">
                <span>Tick Size:</span>
                <span className="text-slate-200">0.25 pt ($5.00)</span>
              </div>
              <div className="flex justify-between text-slate-400">
                <span>Commission:</span>
                <span className="text-slate-200">$2.05/side ($4.10 RT)</span>
              </div>
              <div className="flex justify-between text-slate-400">
                <span>Slippage (1-Tick):</span>
                <span className="text-slate-200">0.25 pt ($10.00 RT)</span>
              </div>
              <div className="pt-1.5 border-t border-white/[0.06] flex justify-between font-bold text-sky-400">
                <span>Total Friction / Trade:</span>
                <span>${NQ_SPECS.roundTripFriction.toFixed(2)}</span>
              </div>
            </div>
          </div>

          {/* Account & Capital Setup */}
          <div className="space-y-3">
            <div className="text-xs font-semibold text-slate-400 uppercase tracking-wider">
              Account Parameters
            </div>

            <div>
              <div className="flex justify-between text-xs mb-1">
                <span className="text-slate-400">Starting Capital</span>
                <span className="font-mono font-bold text-slate-200">${startingCapital.toLocaleString()}</span>
              </div>
              <input
                type="range"
                min="25000"
                max="500000"
                step="25000"
                value={startingCapital}
                onChange={e => setStartingCapital(Number(e.target.value))}
                className="w-full accent-sky-500 h-1.5 bg-slate-800 rounded-lg cursor-pointer"
              />
            </div>

            <div>
              <div className="flex justify-between text-xs mb-1">
                <span className="text-slate-400">Position Size</span>
                <span className="font-mono font-bold text-slate-200">{nqContracts} NQ ({nqContracts * 20} delta)</span>
              </div>
              <div className="grid grid-cols-4 gap-1">
                {[1, 2, 3, 5].map(cnt => (
                  <button
                    key={cnt}
                    onClick={() => setNqContracts(cnt)}
                    className={`py-1 text-xs font-mono font-medium rounded ${
                      nqContracts === cnt
                        ? 'bg-sky-500/20 text-sky-400 border border-sky-500/40 font-bold'
                        : 'bg-[#0E1626] text-slate-400 hover:text-white border border-white/[0.04]'
                    }`}
                  >
                    {cnt}x
                  </button>
                ))}
              </div>
            </div>
          </div>

          {/* Base Data Telemetry */}
          <div className="mt-auto pt-3 border-t border-white/[0.06] text-[11px] text-slate-500 space-y-1 font-mono">
            <div className="flex justify-between">
              <span>Active Bars:</span>
              <span className="text-slate-300">{resampledData.length.toLocaleString()}</span>
            </div>
            <div className="flex justify-between">
              <span>Dataset Range:</span>
              <span className="text-slate-300">2022.10 – 2026.06</span>
            </div>
            <div className="flex justify-between">
              <span>Memory Footprint:</span>
              <span className="text-emerald-400 font-semibold">In-Memory (0 Disk I/O)</span>
            </div>
          </div>
        </aside>

        {/* Main Content Area */}
        <main className="flex-1 overflow-y-auto p-4 md:p-6 space-y-6">
          {/* ========================================================= */}
          {/* TAB 1: AI BACKTEST BOT */}
          {/* ========================================================= */}
          {activeTab === 'backtest' && (
            <div className="space-y-6">
              {/* Header */}
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-3 border-b border-white/[0.06]">
                <div>
                  <h2 className="text-lg font-bold text-white tracking-tight">AI Backtest Bot</h2>
                  <p className="text-xs text-slate-400">
                    Institutional-grade execution with $14.10/trade friction on {selectedTimeframe} timeframe.
                  </p>
                </div>
                <div className="flex items-center gap-2">
                  <button
                    onClick={() => handleParseAndRun()}
                    className="flex items-center gap-2 px-4 py-2 text-xs font-bold text-white bg-sky-600 hover:bg-sky-500 rounded-md shadow-sm transition-all"
                  >
                    <Play className="w-3.5 h-3.5 fill-current" />
                    <span>Execute Backtest</span>
                  </button>
                </div>
              </div>

              {/* Strategy Code Input Box */}
              <div className="rounded-lg border border-white/[0.08] bg-[#0B111D] p-4">
                <div className="flex items-center justify-between mb-2">
                  <div className="flex items-center gap-2 text-xs font-semibold text-slate-300">
                    <Terminal className="w-4 h-4 text-sky-400" />
                    <span>Python Strategy Parameters & Logic</span>
                  </div>
                  <span className="text-[11px] font-mono text-slate-500">Live Vectorized Execution</span>
                </div>
                <textarea
                  value={strategyCode}
                  onChange={e => setStrategyCode(e.target.value)}
                  rows={5}
                  className="w-full bg-[#06090F] border border-white/[0.08] rounded-md p-3 font-mono text-xs text-sky-300 focus:outline-none focus:border-sky-500 resize-none leading-relaxed"
                />
              </div>

              {/* 7 Core Institutional Metric Cards */}
              <div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-7 gap-3">
                <div className="p-3.5 rounded-lg border border-white/[0.08] bg-[#0E1626]">
                  <div className="text-[11px] font-medium text-slate-400 uppercase tracking-wider">Net PnL ($)</div>
                  <div className={`text-xl font-bold font-mono mt-1 ${metrics.netPnL >= 0 ? 'text-emerald-400' : 'text-rose-400'}`}>
                    ${metrics.netPnL.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                  </div>
                  <div className="text-[10px] text-slate-500 font-mono mt-0.5">
                    {metrics.netPnLPct >= 0 ? '+' : ''}{metrics.netPnLPct.toFixed(1)}% Return
                  </div>
                </div>

                <div className="p-3.5 rounded-lg border border-white/[0.08] bg-[#0E1626]">
                  <div className="text-[11px] font-medium text-slate-400 uppercase tracking-wider">Win Rate</div>
                  <div className="text-xl font-bold font-mono text-white mt-1">
                    {metrics.winRate.toFixed(1)}%
                  </div>
                  <div className="text-[10px] text-slate-500 font-mono mt-0.5">
                    {metrics.tradeCount} Trades
                  </div>
                </div>

                <div className="p-3.5 rounded-lg border border-white/[0.08] bg-[#0E1626]">
                  <div className="text-[11px] font-medium text-slate-400 uppercase tracking-wider">Profit Factor</div>
                  <div className={`text-xl font-bold font-mono mt-1 ${metrics.profitFactor >= 1.5 ? 'text-emerald-400' : 'text-amber-400'}`}>
                    {metrics.profitFactor.toFixed(2)}
                  </div>
                  <div className="text-[10px] text-slate-500 font-mono mt-0.5">
                    Gross Win / Loss
                  </div>
                </div>

                <div className="p-3.5 rounded-lg border border-white/[0.08] bg-[#0E1626]">
                  <div className="text-[11px] font-medium text-slate-400 uppercase tracking-wider">Sharpe Ratio</div>
                  <div className="text-xl font-bold font-mono text-sky-400 mt-1">
                    {metrics.sharpe.toFixed(2)}
                  </div>
                  <div className="text-[10px] text-slate-500 font-mono mt-0.5">
                    Risk-Adjusted
                  </div>
                </div>

                <div className="p-3.5 rounded-lg border border-white/[0.08] bg-[#0E1626]">
                  <div className="text-[11px] font-medium text-slate-400 uppercase tracking-wider">Sortino Ratio</div>
                  <div className="text-xl font-bold font-mono text-white mt-1">
                    {metrics.sortino.toFixed(2)}
                  </div>
                  <div className="text-[10px] text-slate-500 font-mono mt-0.5">
                    Downside StdDev
                  </div>
                </div>

                <div className="p-3.5 rounded-lg border border-white/[0.08] bg-[#0E1626]">
                  <div className="text-[11px] font-medium text-slate-400 uppercase tracking-wider">Calmar Ratio</div>
                  <div className="text-xl font-bold font-mono text-white mt-1">
                    {metrics.calmar.toFixed(2)}
                  </div>
                  <div className="text-[10px] text-slate-500 font-mono mt-0.5">
                    CAGR / Max DD
                  </div>
                </div>

                <div className="p-3.5 rounded-lg border border-white/[0.08] bg-[#0E1626]">
                  <div className="text-[11px] font-medium text-slate-400 uppercase tracking-wider">Max Drawdown</div>
                  <div className="text-xl font-bold font-mono text-rose-400 mt-1">
                    {metrics.maxDrawdownPct.toFixed(1)}%
                  </div>
                  <div className="text-[10px] text-slate-500 font-mono mt-0.5">
                    ${metrics.maxDrawdown.toLocaleString()}
                  </div>
                </div>
              </div>

              {/* Charts Section: Equity Curve & Drawdown */}
              <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
                <div className="lg:col-span-2">
                  <EquityCurveChart equityCurve={metrics.equityCurve} drawdownPcts={metrics.drawdownPcts} height={260} />
                </div>
                <div>
                  <DrawdownChart drawdownPcts={metrics.drawdownPcts} height={260} />
                </div>
              </div>

              {/* Monte Carlo & Trade Distribution */}
              <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
                <div className="lg:col-span-2">
                  <MonteCarloChart result={monteCarlo} height={240} />
                </div>
                <div>
                  <TradeDistributionChart pnls={trades.map(t => t.netPnL)} height={240} />
                </div>
              </div>
            </div>
          )}

          {/* ========================================================= */}
          {/* TAB 2: AI IDEAS BOT (Prompt-to-Code) */}
          {/* ========================================================= */}
          {activeTab === 'ideas' && (
            <div className="space-y-6">
              <div className="pb-3 border-b border-white/[0.06]">
                <h2 className="text-lg font-bold text-white tracking-tight">AI Ideas Bot (Prompt-to-Code)</h2>
                <p className="text-xs text-slate-400">
                  Convert algorithmic concepts, session breakout models, or mean-reversion rules into clean, executable Python strategy code.
                </p>
              </div>

              <div className="grid grid-cols-1 lg:grid-cols-3 gap-5">
                <div className="lg:col-span-1 space-y-4">
                  <div>
                    <label className="block text-xs font-semibold text-slate-400 uppercase mb-1.5">
                      Trading Hypothesis or Prompt
                    </label>
                    <textarea
                      value={ideaPrompt}
                      onChange={e => setIdeaPrompt(e.target.value)}
                      rows={5}
                      className="w-full bg-[#0B111D] border border-white/[0.08] rounded-md p-3 text-xs text-slate-200 focus:outline-none focus:border-sky-500 leading-relaxed"
                    />
                  </div>

                  <div>
                    <label className="block text-xs font-semibold text-slate-400 uppercase mb-1.5">
                      Strategy Archetypes
                    </label>
                    <div className="space-y-1.5">
                      {[
                        { id: 'ORB', name: 'US Opening Range Breakout (ORB)' },
                        { id: 'VWAP', name: 'Session VWAP 2.0-Sigma Reversion' },
                        { id: 'MOMENTUM', name: 'Supertrend 3x ATR Momentum Flow' },
                      ].map(concept => (
                        <button
                          key={concept.id}
                          onClick={() => {
                            setSelectedConcept(concept.id);
                            if (concept.id === 'ORB') {
                              setGeneratedCode(`# Strategy: NQ Opening Range Breakout (ORB)
fast_ema = 9
slow_ema = 21
rsi_period = 10
rsi_lower = 32.0
rsi_upper = 68.0
`);
                            } else if (concept.id === 'VWAP') {
                              setGeneratedCode(`# Strategy: Session VWAP 2.0-Sigma Mean Reversion
fast_ema = 16
slow_ema = 44
rsi_period = 14
rsi_lower = 40.0
rsi_upper = 60.0
`);
                            } else {
                              setGeneratedCode(`# Strategy: Supertrend 3x ATR Momentum Flow
fast_ema = 14
slow_ema = 38
rsi_period = 14
rsi_lower = 36.0
rsi_upper = 64.0
`);
                            }
                          }}
                          className={`w-full text-left px-3 py-2 rounded-md text-xs font-medium border transition-colors ${
                            selectedConcept === concept.id
                              ? 'bg-sky-500/20 text-sky-400 border-sky-500/40'
                              : 'bg-[#0E1626] text-slate-400 border-white/[0.04] hover:text-slate-200'
                          }`}
                        >
                          {concept.name}
                        </button>
                      ))}
                    </div>
                  </div>

                  <button
                    onClick={handleGenerateIdea}
                    className="w-full flex items-center justify-center gap-2 px-4 py-2.5 text-xs font-bold text-white bg-sky-600 hover:bg-sky-500 rounded-md transition-colors shadow-sm"
                  >
                    <Lightbulb className="w-4 h-4" />
                    <span>Generate Python Code</span>
                  </button>
                </div>

                <div className="lg:col-span-2 space-y-4">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-semibold text-slate-300">Generated Sandboxed Python Strategy</span>
                    <div className="flex items-center gap-2">
                      <button
                        onClick={() => {
                          navigator.clipboard.writeText(generatedCode);
                          setCodeCopied(true);
                          setTimeout(() => setCodeCopied(false), 2000);
                        }}
                        className="flex items-center gap-1 px-2.5 py-1 text-xs text-slate-300 bg-slate-800 hover:bg-slate-700 rounded border border-white/[0.06]"
                      >
                        {codeCopied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                        <span>{codeCopied ? 'Copied' : 'Copy'}</span>
                      </button>
                      <button
                        onClick={handleSendToBacktest}
                        className="flex items-center gap-1 px-3 py-1 text-xs font-semibold text-white bg-sky-600 hover:bg-sky-500 rounded transition-colors"
                      >
                        <Play className="w-3.5 h-3.5 fill-current" />
                        <span>Send to Backtest Bot</span>
                      </button>
                    </div>
                  </div>

                  <pre className="bg-[#06090F] border border-white/[0.08] rounded-lg p-4 font-mono text-xs text-emerald-300 leading-relaxed overflow-x-auto min-h-[300px]">
                    {generatedCode}
                  </pre>
                </div>
              </div>
            </div>
          )}

          {/* ========================================================= */}
          {/* TAB 3: AI STRATEGY OPTIMIZER */}
          {/* ========================================================= */}
          {activeTab === 'optimizer' && (
            <div className="space-y-6">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-3 border-b border-white/[0.06]">
                <div>
                  <h2 className="text-lg font-bold text-white tracking-tight">AI Strategy Genetic Optimizer</h2>
                  <p className="text-xs text-slate-400">
                    High-speed vectorized perturbation simulation of 10,000 parameter variations on {selectedTimeframe} NQ data.
                  </p>
                </div>
                <div className="flex items-center gap-2">
                  <span className="text-xs text-emerald-400 font-mono font-semibold">10,000 Variations Simulated</span>
                </div>
              </div>

              {/* Top 5 Table */}
              <div className="rounded-lg border border-white/[0.08] bg-[#0B111D] overflow-hidden">
                <div className="px-4 py-3 border-b border-white/[0.06] bg-[#0E1626] flex items-center justify-between">
                  <span className="text-xs font-bold text-slate-300">Top 5 Pareto-Efficient Strategy Candidates</span>
                  <span className="text-[11px] font-mono text-slate-500">Sorted by Composite Sharpe + Profit Factor</span>
                </div>

                <div className="overflow-x-auto">
                  <table className="w-full text-xs text-left font-mono">
                    <thead className="bg-[#06090F] text-slate-400 border-b border-white/[0.06]">
                      <tr>
                        <th className="py-2.5 px-4 font-semibold">Rank</th>
                        <th className="py-2.5 px-4 font-semibold">Fast / Slow EMA</th>
                        <th className="py-2.5 px-4 font-semibold">RSI Range</th>
                        <th className="py-2.5 px-4 font-semibold text-right">Net PnL ($)</th>
                        <th className="py-2.5 px-4 font-semibold text-right">Profit Factor</th>
                        <th className="py-2.5 px-4 font-semibold text-right">Sharpe</th>
                        <th className="py-2.5 px-4 font-semibold text-right">Win Rate</th>
                        <th className="py-2.5 px-4 font-semibold text-right">Max DD</th>
                        <th className="py-2.5 px-4 font-semibold text-right">Action</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-white/[0.04]">
                      {topVariants.map(v => (
                        <tr key={v.rank} className="hover:bg-white/[0.02] transition-colors">
                          <td className="py-3 px-4 font-bold text-sky-400">Variant #{v.rank}</td>
                          <td className="py-3 px-4 text-slate-300">{v.fastEma} / {v.slowEma}</td>
                          <td className="py-3 px-4 text-slate-300">{v.rsiLower} – {v.rsiUpper}</td>
                          <td className={`py-3 px-4 text-right font-bold ${v.netPnL >= 0 ? 'text-emerald-400' : 'text-rose-400'}`}>
                            ${v.netPnL.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                          </td>
                          <td className="py-3 px-4 text-right font-semibold text-amber-400">{v.profitFactor.toFixed(2)}</td>
                          <td className="py-3 px-4 text-right font-bold text-sky-400">{v.sharpe.toFixed(2)}</td>
                          <td className="py-3 px-4 text-right text-slate-300">{v.winRate.toFixed(1)}%</td>
                          <td className="py-3 px-4 text-right text-rose-400">{v.maxDrawdownPct.toFixed(1)}%</td>
                          <td className="py-3 px-4 text-right">
                            <button
                              onClick={() => {
                                const newCode = `# Optimized Candidate #${v.rank}
fast_ema = ${v.fastEma}
slow_ema = ${v.slowEma}
rsi_period = 14
rsi_lower = ${v.rsiLower}.0
rsi_upper = ${v.rsiUpper}.0
`;
                                setStrategyCode(newCode);
                                handleParseAndRun(newCode);
                                setActiveTab('backtest');
                              }}
                              className="px-2 py-1 text-[11px] font-semibold text-sky-400 hover:text-white bg-sky-500/10 hover:bg-sky-500/30 rounded border border-sky-500/30 transition-colors"
                            >
                              Load
                            </button>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>

              {/* 1-Click Clipboard & Download of Winning Variant */}
              {topVariants.length > 0 && (
                <div className="rounded-lg border border-white/[0.08] bg-[#0B111D] p-4 flex flex-col sm:flex-row items-center justify-between gap-4">
                  <div>
                    <h4 className="text-xs font-bold text-white">Winning Candidate: Variant #1</h4>
                    <p className="text-[11px] text-slate-400 font-mono mt-0.5">
                      Net PnL: ${topVariants[0].netPnL.toFixed(2)} · Sharpe: {topVariants[0].sharpe.toFixed(2)} · Fast {topVariants[0].fastEma} / Slow {topVariants[0].slowEma}
                    </p>
                  </div>
                  <div className="flex items-center gap-2 w-full sm:w-auto">
                    <button
                      onClick={() => {
                        const txt = `# NQ QuantLab Top Candidate Variant #1
fast_ema = ${topVariants[0].fastEma}
slow_ema = ${topVariants[0].slowEma}
rsi_period = 14
rsi_lower = ${topVariants[0].rsiLower}.0
rsi_upper = ${topVariants[0].rsiUpper}.0
`;
                        navigator.clipboard.writeText(txt);
                        setOptCopied(true);
                        setTimeout(() => setOptCopied(false), 2000);
                      }}
                      className="flex-1 sm:flex-none flex items-center justify-center gap-1.5 px-3 py-1.5 text-xs font-semibold text-slate-300 bg-slate-800 hover:bg-slate-700 rounded-md border border-white/[0.08]"
                    >
                      {optCopied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                      <span>{optCopied ? 'Copied' : 'Copy Code'}</span>
                    </button>
                    <button
                      onClick={() => {
                        const txt = `# NQ QuantLab Top Candidate Variant #1\nfast_ema = ${topVariants[0].fastEma}\nslow_ema = ${topVariants[0].slowEma}\nrsi_period = 14\nrsi_lower = ${topVariants[0].rsiLower}.0\nrsi_upper = ${topVariants[0].rsiUpper}.0\n`;
                        const blob = new Blob([txt], { type: 'text/plain' });
                        const url = URL.createObjectURL(blob);
                        const a = document.createElement('a');
                        a.href = url;
                        a.download = `NQ_Top_Variant_${selectedTimeframe}.txt`;
                        a.click();
                      }}
                      className="flex-1 sm:flex-none flex items-center justify-center gap-1.5 px-3 py-1.5 text-xs font-semibold text-white bg-sky-600 hover:bg-sky-500 rounded-md shadow-sm"
                    >
                      <Download className="w-3.5 h-3.5" />
                      <span>Download .txt</span>
                    </button>
                  </div>
                </div>
              )}
            </div>
          )}

          {/* ========================================================= */}
          {/* TAB 4: WALK-FORWARD OPTIMIZATION (WFO) */}
          {/* ========================================================= */}
          {activeTab === 'wfo' && (
            <div className="space-y-6">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-3 border-b border-white/[0.06]">
                <div>
                  <h2 className="text-lg font-bold text-white tracking-tight">Walk-Forward Optimization (WFO) Engine</h2>
                  <p className="text-xs text-slate-400">
                    Rolling In-Sample (IS) training and Out-of-Sample (OOS) verification to eliminate look-ahead bias and curve-fitting.
                  </p>
                </div>
                <div className="flex items-center gap-2">
                  <span className={`px-2.5 py-1 rounded text-xs font-bold font-mono ${
                    wfoResult.robustnessPassed
                      ? 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/30'
                      : 'bg-rose-500/20 text-rose-400 border border-rose-500/30'
                  }`}>
                    {wfoResult.robustnessPassed ? 'ROBUST (PASSED)' : 'CURVE-FITTED (FAILED)'}
                  </span>
                </div>
              </div>

              {/* WFO Metric Cards */}
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                <div className="p-4 rounded-lg border border-white/[0.08] bg-[#0E1626]">
                  <div className="text-xs font-medium text-slate-400 uppercase">Walk-Forward Efficiency Index</div>
                  <div className={`text-2xl font-bold font-mono mt-1 ${wfoResult.avgDegradation >= 0.55 ? 'text-emerald-400' : 'text-amber-400'}`}>
                    {wfoResult.avgDegradation.toFixed(2)}
                  </div>
                  <div className="text-[11px] text-slate-500 font-mono mt-0.5">
                    OOS Sharpe / IS Sharpe (Target &gt; 0.55)
                  </div>
                </div>

                <div className="p-4 rounded-lg border border-white/[0.08] bg-[#0E1626]">
                  <div className="text-xs font-medium text-slate-400 uppercase">Stitched Out-of-Sample PnL</div>
                  <div className="text-2xl font-bold font-mono text-white mt-1">
                    ${(wfoResult.stitchedEquity[wfoResult.stitchedEquity.length - 1] - 100000).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                  </div>
                  <div className="text-[11px] text-slate-500 font-mono mt-0.5">
                    Cumulative OOS Master Performance
                  </div>
                </div>

                <div className="p-4 rounded-lg border border-white/[0.08] bg-[#0E1626]">
                  <div className="text-xs font-medium text-slate-400 uppercase">Split Calibration Folds</div>
                  <div className="text-2xl font-bold font-mono text-sky-400 mt-1">
                    {wfoSplits} Folds
                  </div>
                  <div className="text-[11px] text-slate-500 font-mono mt-0.5">
                    {Math.round(wfoIsRatio * 100)}% In-Sample / {Math.round((1 - wfoIsRatio) * 100)}% Out-of-Sample
                  </div>
                </div>
              </div>

              {/* Stitched Master Equity Curve */}
              <EquityCurveChart equityCurve={wfoResult.stitchedEquity} drawdownPcts={[]} height={240} />

              {/* Window-by-Window Table Breakdown */}
              <div className="rounded-lg border border-white/[0.08] bg-[#0B111D] overflow-hidden">
                <div className="px-4 py-3 border-b border-white/[0.06] bg-[#0E1626] text-xs font-bold text-slate-300">
                  Rolling In-Sample & Out-of-Sample Window Breakdown
                </div>
                <div className="overflow-x-auto">
                  <table className="w-full text-xs text-left font-mono">
                    <thead className="bg-[#06090F] text-slate-400 border-b border-white/[0.06]">
                      <tr>
                        <th className="py-2.5 px-4 font-semibold">Window</th>
                        <th className="py-2.5 px-4 font-semibold">Date Range</th>
                        <th className="py-2.5 px-4 font-semibold text-right">IS Sharpe</th>
                        <th className="py-2.5 px-4 font-semibold text-right">OOS Sharpe</th>
                        <th className="py-2.5 px-4 font-semibold text-right">Degradation Ratio</th>
                        <th className="py-2.5 px-4 font-semibold text-right">OOS Net PnL</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-white/[0.04]">
                      {wfoResult.windows.map((w, idx) => (
                        <tr key={idx} className="hover:bg-white/[0.02]">
                          <td className="py-3 px-4 font-bold text-sky-400">{w.window}</td>
                          <td className="py-3 px-4 text-slate-300">{w.dateRange}</td>
                          <td className="py-3 px-4 text-right text-slate-200">{w.isSharpe.toFixed(2)}</td>
                          <td className="py-3 px-4 text-right font-bold text-white">{w.oosSharpe.toFixed(2)}</td>
                          <td className={`py-3 px-4 text-right font-bold ${w.degradation >= 0.55 ? 'text-emerald-400' : 'text-rose-400'}`}>
                            {w.degradation.toFixed(2)}
                          </td>
                          <td className={`py-3 px-4 text-right font-bold ${w.oosNetPnL >= 0 ? 'text-emerald-400' : 'text-rose-400'}`}>
                            ${w.oosNetPnL.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          )}

          {/* ========================================================= */}
          {/* TAB 5: BENCHMARK ALPHA & BETA COMPARISON */}
          {/* ========================================================= */}
          {activeTab === 'benchmark' && (
            <div className="space-y-6">
              <div className="pb-3 border-b border-white/[0.06]">
                <h2 className="text-lg font-bold text-white tracking-tight">Benchmark Alpha & Beta Analysis</h2>
                <p className="text-xs text-slate-400">
                  Side-by-side performance comparison against a passive CME Nasdaq-100 buy-and-hold baseline over the identical period.
                </p>
              </div>

              {/* Comparative HUD */}
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
                <div className="p-4 rounded-lg border border-white/[0.08] bg-[#0E1626]">
                  <div className="text-xs font-medium text-slate-400 uppercase">Strategy Return</div>
                  <div className="text-2xl font-bold font-mono text-emerald-400 mt-1">
                    {metrics.netPnLPct >= 0 ? '+' : ''}{metrics.netPnLPct.toFixed(1)}%
                  </div>
                  <div className="text-[11px] text-slate-500 font-mono mt-0.5">
                    Net PnL: ${metrics.netPnL.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                  </div>
                </div>

                <div className="p-4 rounded-lg border border-white/[0.08] bg-[#0E1626]">
                  <div className="text-xs font-medium text-slate-400 uppercase">Passive NQ Buy & Hold</div>
                  <div className="text-2xl font-bold font-mono text-sky-400 mt-1">
                    +{benchmarkStats.bhReturn.toFixed(1)}%
                  </div>
                  <div className="text-[11px] text-slate-500 font-mono mt-0.5">
                    CME Benchmark Index
                  </div>
                </div>

                <div className="p-4 rounded-lg border border-white/[0.08] bg-[#0E1626]">
                  <div className="text-xs font-medium text-slate-400 uppercase">Alpha (Annualized Excess)</div>
                  <div className={`text-2xl font-bold font-mono mt-1 ${benchmarkStats.alpha >= 0 ? 'text-emerald-400' : 'text-rose-400'}`}>
                    {benchmarkStats.alpha >= 0 ? '+' : ''}{benchmarkStats.alpha.toFixed(2)}%
                  </div>
                  <div className="text-[11px] text-slate-500 font-mono mt-0.5">
                    Jensen's Alpha
                  </div>
                </div>

                <div className="p-4 rounded-lg border border-white/[0.08] bg-[#0E1626]">
                  <div className="text-xs font-medium text-slate-400 uppercase">Beta (Market Sensitivity)</div>
                  <div className="text-2xl font-bold font-mono text-white mt-1">
                    {benchmarkStats.beta.toFixed(2)}
                  </div>
                  <div className="text-[11px] text-slate-500 font-mono mt-0.5">
                    Market Correlation Factor
                  </div>
                </div>
              </div>

              {/* Side-by-Side Normalized Capital Chart */}
              <div className="rounded-lg border border-white/[0.08] bg-[#0B111D] p-4">
                <div className="flex items-center justify-between mb-3 text-xs">
                  <span className="font-semibold text-slate-300">Normalized Performance Comparison</span>
                  <div className="flex items-center gap-4 text-xs font-mono">
                    <span className="text-sky-400">● Strategy (After Friction)</span>
                    <span className="text-slate-400">-- Passive NQ Baseline</span>
                  </div>
                </div>

                <EquityCurveChart equityCurve={metrics.equityCurve} drawdownPcts={[]} height={280} />
              </div>
            </div>
          )}

          {/* ========================================================= */}
          {/* TAB 6: MANUAL PAPER TRADING TERMINAL */}
          {/* ========================================================= */}
          {activeTab === 'papertrading' && (
            <div className="space-y-6">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-3 border-b border-white/[0.06]">
                <div>
                  <h2 className="text-lg font-bold text-white tracking-tight">Interactive Paper Trading Terminal</h2>
                  <p className="text-xs text-slate-400">
                    Live manual sandbox execution with TradingView-style candlestick chart and ephemeral session stats.
                  </p>
                </div>
                <div className="flex items-center gap-2">
                  <button
                    onClick={handleFinishSession}
                    className="px-3.5 py-1.5 text-xs font-bold text-white bg-rose-600 hover:bg-rose-500 rounded-md transition-colors"
                  >
                    Finish Session & Itemize
                  </button>
                  <button
                    onClick={handleResetSession}
                    className="px-3 py-1.5 text-xs font-semibold text-slate-300 bg-slate-800 hover:bg-slate-700 rounded-md border border-white/[0.08]"
                  >
                    Reset
                  </button>
                </div>
              </div>

              {/* HUD Banner */}
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                <div className="p-3.5 rounded-lg border border-white/[0.08] bg-[#0E1626]">
                  <div className="text-[11px] font-medium text-slate-400 uppercase">Account Balance</div>
                  <div className="text-xl font-bold font-mono text-white mt-1">
                    ${paperBalance.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                  </div>
                  <div className="text-[10px] text-slate-500 font-mono">Liquid Cash</div>
                </div>

                <div className="p-3.5 rounded-lg border border-white/[0.08] bg-[#0E1626]">
                  <div className="text-[11px] font-medium text-slate-400 uppercase">Current Position</div>
                  <div className={`text-xl font-bold font-mono mt-1 ${
                    paperPosition === 'LONG' ? 'text-emerald-400' : paperPosition === 'SHORT' ? 'text-rose-400' : 'text-slate-400'
                  }`}>
                    {paperPosition === 'FLAT' ? 'FLAT' : `${paperPosition} ${paperContracts}x`}
                  </div>
                  <div className="text-[10px] text-slate-500 font-mono">
                    {paperPosition !== 'FLAT' ? `@ ${paperEntryPrice.toFixed(2)}` : 'No Open Risk'}
                  </div>
                </div>

                <div className="p-3.5 rounded-lg border border-white/[0.08] bg-[#0E1626]">
                  <div className="text-[11px] font-medium text-slate-400 uppercase">Unrealized PnL</div>
                  <div className={`text-xl font-bold font-mono mt-1 ${unrealizedPnL >= 0 ? 'text-emerald-400' : 'text-rose-400'}`}>
                    ${unrealizedPnL.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                  </div>
                  <div className="text-[10px] text-slate-500 font-mono">Floating Delta</div>
                </div>

                <div className="p-3.5 rounded-lg border border-white/[0.08] bg-[#0E1626]">
                  <div className="text-[11px] font-medium text-slate-400 uppercase">Session Orders</div>
                  <div className="text-xl font-bold font-mono text-sky-400 mt-1">
                    {paperTrades.length}
                  </div>
                  <div className="text-[10px] text-slate-500 font-mono">Closed Executions</div>
                </div>
              </div>

              {/* Order Execution Bar */}
              <div className="rounded-lg border border-white/[0.08] bg-[#0B111D] p-4 flex flex-wrap items-center justify-between gap-4">
                <div className="flex items-center gap-3">
                  <div className="flex items-center gap-2">
                    <span className="text-xs text-slate-400 font-medium">Contracts:</span>
                    <select
                      value={paperContracts}
                      onChange={e => setPaperContracts(Number(e.target.value))}
                      className="bg-[#06090F] border border-white/[0.08] rounded px-2.5 py-1 text-xs font-mono text-white focus:outline-none"
                    >
                      <option value={1}>1 NQ</option>
                      <option value={2}>2 NQ</option>
                      <option value={3}>3 NQ</option>
                      <option value={5}>5 NQ</option>
                      <option value={10}>10 NQ</option>
                    </select>
                  </div>
                  <span className="text-xs text-slate-500 font-mono">
                    Friction: ${(NQ_SPECS.roundTripFriction * paperContracts).toFixed(2)}/RT
                  </span>
                </div>

                <div className="flex items-center gap-2 w-full sm:w-auto">
                  <button
                    onClick={handleBuyMarket}
                    className="flex-1 sm:flex-none px-5 py-2 text-xs font-bold text-white bg-emerald-600 hover:bg-emerald-500 rounded-md transition-colors shadow-sm"
                  >
                    BUY / LONG
                  </button>
                  <button
                    onClick={handleSellMarket}
                    className="flex-1 sm:flex-none px-5 py-2 text-xs font-bold text-white bg-rose-600 hover:bg-rose-500 rounded-md transition-colors shadow-sm"
                  >
                    SELL / SHORT
                  </button>
                  <button
                    onClick={handleCloseMarket}
                    disabled={paperPosition === 'FLAT'}
                    className="flex-1 sm:flex-none px-4 py-2 text-xs font-semibold text-slate-300 bg-slate-800 hover:bg-slate-700 disabled:opacity-40 disabled:cursor-not-allowed rounded-md border border-white/[0.08] transition-colors"
                  >
                    FLAT
                  </button>
                </div>
              </div>

              {/* Interactive TradingView Candlestick Chart */}
              <TradingViewChart
                candles={resampledData}
                activePosition={{
                  type: paperPosition,
                  entryPrice: paperEntryPrice,
                  contracts: paperContracts,
                }}
                height={420}
              />

              {/* Itemized Session Performance Report (Generated ephemerally) */}
              {isSessionFinished && (
                <div className="rounded-lg border border-sky-500/30 bg-[#0B111D] p-5 space-y-4">
                  <div className="flex items-center justify-between pb-3 border-b border-white/[0.08]">
                    <div className="flex items-center gap-2">
                      <Shield className="w-5 h-5 text-sky-400" />
                      <h3 className="text-base font-bold text-white">Itemized Session Performance Audit</h3>
                    </div>
                    <span className="text-xs font-mono text-sky-400">Ephemeral In-Memory Receipt</span>
                  </div>

                  <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs font-mono">
                    <div className="bg-[#0E1626] p-3 rounded border border-white/[0.06]">
                      <span className="text-slate-400">Realized PnL</span>
                      <div className={`text-lg font-bold mt-0.5 ${
                        paperBalance - startingCapital >= 0 ? 'text-emerald-400' : 'text-rose-400'
                      }`}>
                        ${(paperBalance - startingCapital).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                      </div>
                    </div>
                    <div className="bg-[#0E1626] p-3 rounded border border-white/[0.06]">
                      <span className="text-slate-400">Total Fills</span>
                      <div className="text-lg font-bold text-white mt-0.5">{paperTrades.length}</div>
                    </div>
                    <div className="bg-[#0E1626] p-3 rounded border border-white/[0.06]">
                      <span className="text-slate-400">Win Rate</span>
                      <div className="text-lg font-bold text-white mt-0.5">
                        {paperTrades.length > 0
                          ? ((paperTrades.filter(t => t.netPnL > 0).length / paperTrades.length) * 100).toFixed(1)
                          : 0}%
                      </div>
                    </div>
                    <div className="bg-[#0E1626] p-3 rounded border border-white/[0.06]">
                      <span className="text-slate-400">Ending Balance</span>
                      <div className="text-lg font-bold text-sky-400 mt-0.5">
                        ${paperBalance.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                      </div>
                    </div>
                  </div>

                  {/* Itemized Order Log Table */}
                  <div className="overflow-x-auto rounded border border-white/[0.06]">
                    <table className="w-full text-xs text-left font-mono">
                      <thead className="bg-[#06090F] text-slate-400 border-b border-white/[0.06]">
                        <tr>
                          <th className="py-2 px-3">Order ID</th>
                          <th className="py-2 px-3">Type</th>
                          <th className="py-2 px-3 text-right">Entry</th>
                          <th className="py-2 px-3 text-right">Exit</th>
                          <th className="py-2 px-3 text-right">Friction</th>
                          <th className="py-2 px-3 text-right">Net PnL</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-white/[0.04]">
                        {paperTrades.map(trade => (
                          <tr key={trade.id} className="hover:bg-white/[0.02]">
                            <td className="py-2 px-3 text-slate-400">{trade.id}</td>
                            <td className="py-2 px-3 font-semibold text-sky-400">{trade.type}</td>
                            <td className="py-2 px-3 text-right text-slate-300">{trade.entryPrice.toFixed(2)}</td>
                            <td className="py-2 px-3 text-right text-slate-300">{trade.exitPrice.toFixed(2)}</td>
                            <td className="py-2 px-3 text-right text-slate-400">${trade.friction.toFixed(2)}</td>
                            <td className={`py-2 px-3 text-right font-bold ${trade.netPnL >= 0 ? 'text-emerald-400' : 'text-rose-400'}`}>
                              ${trade.netPnL.toFixed(2)}
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              )}
            </div>
          )}
        </main>
      </div>

      {/* Streamlit Python Source Inspection Modal */}
      <StreamlitSourceModal
        isOpen={isSourceModalOpen}
        onClose={() => setIsSourceModalOpen(false)}
      />
    </div>
  );
}
